services:
  web:
    container_name: inandout-container
    image: inandoutswyp/inandout:latest
    env_file:
      - .env
    expose:
      - 9000
    ports:
      - 9000:9000
    networks:
      - inandout-network

networks:
  inandout-network:
    driver: bridge